name: Ebuild Tests

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    # Prepare the environment
    - name: Prepare
      id: prepare
      run: |
        echo "::set-output name=date::$(date +"%Y%m%d")"
        mkdir ~/distfiles ~/binpkgs

    # Cache distfiles and binary packages    
    - name: Cache distfiles
      id: cache-distfiles
      uses: gerbal/always-cache@v1.0.3
      with:
        path: ~/distfiles
        key: distfiles-${{ steps.prepare.outputs.datetime }}
        restore-keys: |
          distfiles-${{ steps.prepare.outputs.datetime }}
          distfiles
    - name: Cache binpkgs
      id: cache-binpkgs
      uses: gerbal/always-cache@v1.0.3
      with:
        path: ~/binpkgs
        key: binpkgs-${{ steps.prepare.outputs.datetime }}
        restore-keys: |
          binpkgs-${{ steps.prepare.outputs.datetime }}
          binpkgs

    - uses: actions/checkout@master

    - uses: hacking-gentoo/action-ebuild-test@master
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
